#!/usr/bin/env bash
# ==============================================================================
# test/golden.sh — Node 版 vs Bash 版 golden 对拍（v2.1.0 起为「剥离对拍」）
# ==============================================================================
# 验收红线：Node v2.1.0 输出经剥掉区间列（[Ls-Le] → [Ls]）后，与 Bash 版
# （wisdom_app 仓，只读，冻结在 v1.7.0）同参输出 normalize 后 diff 必须为空——
# 证明符号区演进只加了区间列、零行为漂移。
# 快照：test/golden/snapshot/*.md 保存 v2.1.0 原文（剥离前），首次缺失时自动
# 录入；`--snapshot` 显式对当前输出对快照 diff 防回归——仓库或扫描器演进后
# 属预期失败，需 rm 快照后有意识重录。
# 连续执行两版（同一代码快照），避免 worktree 变化造成假差异。
# ==============================================================================
set -u

NODE_CLI="$(cd "$(dirname "$0")/.." && pwd)/bin/scan_repo_map.mjs"
BASH_CLI="/Users/xuehai/development/wisdom_app/scripts/scan_repo_map.sh"
SNAPSHOT_DIR="$(cd "$(dirname "$0")" && pwd)/golden/snapshot"
OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

WITH_SNAPSHOT=0
[[ "${1:-}" == "--snapshot" ]] && WITH_SNAPSHOT=1

# 头部 normalize（与 test/helpers.mjs 等价）：删易变行与空行。无参数时读 stdin。
normalize() {
  sed -E 's/^# Generated by:.*/# Generated by:/; s/^# Scanner Version:.*//; s/^# ast-grep Version:.*//' ${1:+"$1"} \
    | grep -vE '^# (Source Commit|Worktree|Merged from|Combined by):' \
    | grep -v '^$'
}

# 剥离符号行区间列：[L<start>-L<end>] → [L<start>]（import/api 行本就是 [L<n>]，不受影响）
strip_intervals() {
  sed -E 's/\[L([0-9]+)-L[0-9]+\]/[L\1]/g' "$1"
}

# golden 目录列表：名称|目录|快照文件名
GOLDENS=(
  "scan_repo_map 自身|$HOME/development/scan_repo_map|scan_repo_map.md"
  "wisdom_app lib|$HOME/development/wisdom_app/lib|wisdom_app_lib.md"
)

rc=0
for entry in "${GOLDENS[@]}"; do
  name="${entry%%|*}"; rest="${entry#*|}"
  dir="${rest%%|*}"; snap="${rest#*|}"
  echo "== golden: $name ($dir) =="
  bash "$BASH_CLI" -d "$dir" -n golden -o "$OUT/a.md" >"$OUT/a.out" 2>"$OUT/a.err"
  bash_rc=$?
  node "$NODE_CLI" -d "$dir" -n golden -o "$OUT/b.md" >"$OUT/b.out" 2>"$OUT/b.err"
  node_rc=$?
  if [[ $bash_rc -ne 0 || $node_rc -ne 0 ]]; then
    echo "❌ 扫描退出码非零（bash=$bash_rc node=$node_rc）"
    cat "$OUT/a.err" "$OUT/b.err"
    rc=1
    continue
  fi
  # 剥离对拍：Node 剥区间后与 Bash normalize 直比
  if diff -u <(normalize "$OUT/a.md") <(strip_intervals "$OUT/b.md" | normalize) >"$OUT/diff.txt"; then
    echo "✅ 剥离对拍空 diff（区间列之外零漂移）：$(tail -1 "$OUT/a.out") / $(tail -1 "$OUT/b.out")"
  else
    echo "❌ 剥离后仍有差异："
    cat "$OUT/diff.txt"
    rc=1
  fi
  # 快照基线：缺失时录入原文；--snapshot 时对快照 diff 防回归
  if [[ ! -f "$SNAPSHOT_DIR/$snap" ]]; then
    mkdir -p "$SNAPSHOT_DIR"
    cp "$OUT/b.md" "$SNAPSHOT_DIR/$snap"
    echo "📸 快照已录入：$SNAPSHOT_DIR/$snap"
  elif [[ "$WITH_SNAPSHOT" == "1" ]]; then
    if diff -u <(normalize "$SNAPSHOT_DIR/$snap") <(normalize "$OUT/b.md") >"$OUT/snapdiff.txt"; then
      echo "✅ 快照一致：$SNAPSHOT_DIR/$snap"
    else
      echo "❌ 与快照不一致（仓库或扫描器演进后属预期，需 rm 快照后有意识重录）："
      cat "$OUT/snapdiff.txt"
      rc=1
    fi
  fi
done
exit $rc
