#!/usr/bin/env bash
# ==============================================================================
# test/golden.sh — Node 版 vs Bash 版 golden 对拍
# ==============================================================================
# 1. 用 Bash 版（wisdom_app 仓，只读）对 golden 目录各跑一次，得基线 A；
# 2. 用 Node 版同参数跑，得 B；
# 3. 经 normalize（删 Generated by / Scanner Version / ast-grep Version /
#    Source Commit / Worktree / Merged from / Combined by 行，删空行）后 diff -u 必须为空。
# 连续执行两版（同一代码快照），避免 worktree 变化造成假差异。
# ==============================================================================
set -u

NODE_CLI="$(cd "$(dirname "$0")/.." && pwd)/bin/scan_repo_map.mjs"
BASH_CLI="/Users/xuehai/development/wisdom_app/scripts/scan_repo_map.sh"
OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

normalize() {
  sed -E 's/^# Generated by:.*/# Generated by:/; s/^# Scanner Version:.*//; s/^# ast-grep Version:.*//' "$1" \
    | grep -vE '^# (Source Commit|Worktree|Merged from|Combined by):' \
    | grep -v '^$'
}

# golden 目录列表：名称|目录
GOLDENS=(
  "scan_repo_map 自身|$HOME/development/scan_repo_map"
  "wisdom_app lib|$HOME/development/wisdom_app/lib"
)

rc=0
for entry in "${GOLDENS[@]}"; do
  name="${entry%%|*}"
  dir="${entry#*|}"
  echo "== golden: $name ($dir) =="
  bash "$BASH_CLI" -d "$dir" -n golden -o "$OUT/a.md" >"$OUT/a.out" 2>"$OUT/a.err"
  bash_rc=$?
  node "$NODE_CLI" -d "$dir" -n golden -o "$OUT/b.md" >"$OUT/b.out" 2>"$OUT/b.err"
  node_rc=$?
  if [[ $bash_rc -ne 0 || $node_rc -ne 0 ]]; then
    echo "❌ 扫描退出码非零（bash=$bash_rc node=$node_rc）"
    cat "$OUT/a.err" "$OUT/b.err"
    rc=1
    continue
  fi
  if diff -u <(normalize "$OUT/a.md") <(normalize "$OUT/b.md") >"$OUT/diff.txt"; then
    echo "✅ 逐字节一致（normalize 后 diff 为空）：$(tail -1 "$OUT/a.out") / $(tail -1 "$OUT/b.out")"
  else
    echo "❌ 存在差异："
    cat "$OUT/diff.txt"
    rc=1
  fi
done
exit $rc
