// 共享测试辅助：地图头部归一化（与 test/golden.sh 的 bash normalize 等价）
// 删除易变行：Generated by / Scanner Version / ast-grep Version /
// Source Commit / Worktree / Merged from / Combined by，以及空行。
import { readFileSync } from 'node:fs'

export function normalizeMap(file) {
  return readFileSync(file, 'utf8').split('\n')
    .map((l) => l
      .replace(/^# Generated by:.*/, '# Generated by:')
      .replace(/^# Scanner Version:.*/, '')
      .replace(/^# ast-grep Version:.*/, ''))
    .filter((l) => !/^# (Source Commit|Worktree|Merged from|Combined by):/.test(l))
    .filter((l) => l !== '')
}
