// Android (Kotlin / Java) + iOS/Native (Swift / C / C++) 语言规则 — 自 rules_native.sh 逐条机械移植（勿手改 pattern，改动须与 Bash 版同步）
// crosslayer: true 的规则仅在 CROSSLAYER=1 时执行（对应 Bash 版 if CROSSLAYER==1 块）

export const RULES = [
  { fn: "kinds", lang: "kotlin", kind: "class_declaration", label: "class", auto: true },
  { fn: "kinds", lang: "kotlin", kind: "object_declaration", label: "object-singleton" },
  { fn: "symbols", lang: "kotlin", pattern: "class $NAME { $$$ }", label: "class" },
  { fn: "symbols", lang: "kotlin", pattern: "class $NAME($$$) { $$$ }", label: "class" },
  { fn: "symbols", lang: "kotlin", pattern: "class $NAME : $$$ { $$$ }", label: "class" },
  { fn: "symbols", lang: "kotlin", pattern: "class $NAME($$$) : $$$ { $$$ }", label: "class" },
  { fn: "symbols", lang: "kotlin", pattern: "sealed class $NAME { $$$ }", label: "sealed-class" },
  { fn: "symbols", lang: "kotlin", pattern: "enum class $NAME { $$$ }", label: "enum" },
  { fn: "symbols", lang: "kotlin", pattern: "@Composable\nfun $NAME($$$) { $$$ }", label: "composable" },
  { fn: "symbols", lang: "kotlin", pattern: "@Composable\nfun $NAME($$$) = $$$", label: "composable" },
  { fn: "symbols", lang: "kotlin", pattern: "fun $NAME($$$) { $$$ }", label: "fun" },
  { fn: "symbols", lang: "kotlin", pattern: "fun $NAME($$$): $RET { $$$ }", label: "fun" },
  { fn: "symbols", lang: "kotlin", pattern: "fun $NAME($$$) = $$$", label: "fun" },
  { fn: "symbols", lang: "kotlin", pattern: "fun $NAME($$$): $RET = $$$", label: "fun" },
  { fn: "symbols", lang: "kotlin", pattern: "suspend fun $NAME($$$) { $$$ }", label: "suspend-fun" },
  { fn: "symbols", lang: "kotlin", pattern: "suspend fun $NAME($$$): $RET { $$$ }", label: "suspend-fun" },
  { fn: "symbols", lang: "kotlin", pattern: "fun $RECEIVER.$NAME($$$) { $$$ }", label: "extension-fun" },
  { fn: "symbols", lang: "kotlin", pattern: "fun $RECEIVER.$NAME($$$): $RET { $$$ }", label: "extension-fun" },
  { fn: "symbols", lang: "kotlin", pattern: "suspend fun $RECEIVER.$NAME($$$) { $$$ }", label: "suspend-extension-fun" },
  { fn: "symbols", lang: "kotlin", pattern: "suspend fun $RECEIVER.$NAME($$$): $RET { $$$ }", label: "suspend-extension-fun" },
  { fn: "symbols", lang: "kotlin", pattern: "@Dao\ninterface $NAME { $$$ }", label: "room-dao" },
  { fn: "kindJq", lang: "java", kind: "class_declaration", jq: "classlike" },
  { fn: "kindJq", lang: "java", kind: "interface_declaration", jq: "classlike" },
  { fn: "kindJq", lang: "java", kind: "enum_declaration", jq: "classlike" },
  { fn: "kindJq", lang: "java", kind: "annotation_type_declaration", jq: "classlike" },
  { fn: "kinds", lang: "java", kind: "method_declaration", label: "method" },
  { fn: "kinds", lang: "java", kind: "constructor_declaration", label: "constructor" },
  { fn: "kindJq", lang: "swift", kind: "class_declaration", jq: "classlike" },
  { fn: "symbols", lang: "swift", pattern: "protocol $NAME { $$$ }", label: "protocol" },
  { fn: "symbols", lang: "swift", pattern: "protocol $NAME : $$$ { $$$ }", label: "protocol" },
  { fn: "symbols", lang: "swift", pattern: "typealias $NAME = $$$", label: "typealias" },
  { fn: "symbols", lang: "swift", pattern: "func $NAME($$$) { $$$ }", label: "func" },
  { fn: "symbols", lang: "swift", pattern: "func $NAME($$$) -> $$$ { $$$ }", label: "func" },
  { fn: "symbols", lang: "swift", pattern: "func $NAME($$$) async { $$$ }", label: "async-func" },
  { fn: "symbols", lang: "swift", pattern: "func $NAME($$$) async throws -> $$$ { $$$ }", label: "async-throws-func" },
  { fn: "symbols", lang: "swift", pattern: "static func $NAME($$$) { $$$ }", label: "static-func" },
  { fn: "symbols", lang: "swift", pattern: "@objc func $NAME($$$) { $$$ }", label: "objc-func" },
  { fn: "kinds", lang: "c", kind: "struct_specifier", label: "c-struct" },
  { fn: "kinds", lang: "c", kind: "enum_specifier", label: "c-enum" },
  { fn: "symbols", lang: "c", pattern: "$RET $NAME($$$) { $$$ }", label: "c-func" },
  { fn: "kinds", lang: "cpp", kind: "class_specifier", label: "cpp-class" },
  { fn: "kinds", lang: "cpp", kind: "struct_specifier", label: "cpp-struct" },
  { fn: "kinds", lang: "cpp", kind: "enum_specifier", label: "cpp-enum" },
  { fn: "symbols", lang: "cpp", pattern: "namespace $NAME { $$$ }", label: "cpp-namespace" },
  { fn: "symbols", lang: "cpp", pattern: "$RET $NAME($$$) { $$$ }", label: "cpp-func" },
  { fn: "symbols", lang: "cpp", pattern: "$RET $CLASS::$NAME($$$) { $$$ }", label: "cpp-method" },

  // --- 跨层：导入抽取 / API 路径（--no-crosslayer 时跳过） ---
  { fn: "import", lang: "java", pattern: "import $PACKAGE;", metavar: "PACKAGE", clean: "raw" , crosslayer: true },
  { fn: "import", lang: "java", pattern: "import static $PACKAGE;", metavar: "PACKAGE", clean: "raw" , crosslayer: true },
  { fn: "import", lang: "kotlin", pattern: "import $PACKAGE", metavar: "PACKAGE", clean: "raw" , crosslayer: true },
  { fn: "import", lang: "swift", pattern: "import $MODULE", metavar: "MODULE", clean: "raw" , crosslayer: true },
];
