// Python (FastAPI / Django / Pydantic / AI Services) 语言规则 — 自 rules_python.sh 逐条机械移植（勿手改 pattern，改动须与 Bash 版同步）
// crosslayer: true 的规则仅在 CROSSLAYER=1 时执行（对应 Bash 版 if CROSSLAYER==1 块）

export const RULES = [
  { fn: "symbols", lang: "python", pattern: "class $NAME: $$$", label: "class" },
  { fn: "symbols", lang: "python", pattern: "class $NAME($$$): $$$", label: "class" },
  { fn: "symbols", lang: "python", pattern: "@dataclass\nclass $NAME: $$$", label: "dataclass" },
  { fn: "symbols", lang: "python", pattern: "@dataclass($$$)\nclass $NAME: $$$", label: "dataclass" },
  { fn: "symbols", lang: "python", pattern: "class $NAME(BaseModel): $$$", label: "pydantic-model" },
  { fn: "symbols", lang: "python", pattern: "class $NAME(Base): $$$", label: "orm-model" },
  { fn: "symbols", lang: "python", pattern: "class $NAME(models.Model): $$$", label: "django-model" },
  { fn: "symbols", lang: "python", pattern: "class $NAME(TypedDict): $$$", label: "typed-dict" },
  { fn: "symbols", lang: "python", pattern: "class $NAME(Enum): $$$", label: "enum" },
  { fn: "symbols", lang: "python", pattern: "class $NAME(str, Enum): $$$", label: "enum" },
  { fn: "symbols", lang: "python", pattern: "class $NAME(IntEnum): $$$", label: "enum" },
  { fn: "symbols", lang: "python", pattern: "class $NAME(Model): $$$", label: "tortoise-model" },
  { fn: "symbols", lang: "python", pattern: "class $NAME(models.Model): $$$", label: "tortoise-model" },
  { fn: "symbols", lang: "python", pattern: "class $NAME(Model, $$$): $$$", label: "tortoise-model" },
  { fn: "symbols", lang: "python", pattern: "class $NAME(models.Model, $$$): $$$", label: "tortoise-model" },
  { fn: "symbols", lang: "python", pattern: "class $NAME($$$, Model): $$$", label: "tortoise-model" },
  { fn: "symbols", lang: "python", pattern: "class $NAME($$$, models.Model): $$$", label: "tortoise-model" },
  { fn: "symbols", lang: "python", pattern: "$NAME = pydantic_model_creator($$$)", label: "tortoise-pydantic" },
  { fn: "symbols", lang: "python", pattern: "$NAME = pydantic_queryset_creator($$$)", label: "tortoise-pydantic" },
  { fn: "symbols", lang: "python", pattern: "def $NAME($$$): $$$", label: "def" },
  { fn: "symbols", lang: "python", pattern: "async def $NAME($$$): $$$", label: "async-def" },
  { fn: "symbols", lang: "python", pattern: "@router.get($$$)\nasync def $NAME($$$): $$$", label: "api-get" },
  { fn: "symbols", lang: "python", pattern: "@router.post($$$)\nasync def $NAME($$$): $$$", label: "api-post" },
  { fn: "symbols", lang: "python", pattern: "@router.put($$$)\nasync def $NAME($$$): $$$", label: "api-put" },
  { fn: "symbols", lang: "python", pattern: "@router.delete($$$)\nasync def $NAME($$$): $$$", label: "api-delete" },
  { fn: "symbols", lang: "python", pattern: "@router.patch($$$)\nasync def $NAME($$$): $$$", label: "api-patch" },
  { fn: "symbols", lang: "python", pattern: "@app.get($$$)\nasync def $NAME($$$): $$$", label: "api-get" },
  { fn: "symbols", lang: "python", pattern: "@app.post($$$)\nasync def $NAME($$$): $$$", label: "api-post" },
  { fn: "symbols", lang: "python", pattern: "@app.put($$$)\nasync def $NAME($$$): $$$", label: "api-put" },
  { fn: "symbols", lang: "python", pattern: "@app.delete($$$)\nasync def $NAME($$$): $$$", label: "api-delete" },
  { fn: "symbols", lang: "python", pattern: "@app.route($$$)\ndef $NAME($$$): $$$", label: "api-route" },
  { fn: "symbols", lang: "python", pattern: "@router.get($$$)\ndef $NAME($$$): $$$", label: "api-get" },
  { fn: "symbols", lang: "python", pattern: "@router.post($$$)\ndef $NAME($$$): $$$", label: "api-post" },
  { fn: "symbols", lang: "python", pattern: "@celery.task\ndef $NAME($$$): $$$", label: "celery-task" },
  { fn: "symbols", lang: "python", pattern: "@celery.task($$$)\ndef $NAME($$$): $$$", label: "celery-task" },
  { fn: "symbols", lang: "python", pattern: "@shared_task\ndef $NAME($$$): $$$", label: "celery-task" },
  { fn: "symbols", lang: "python", pattern: "@shared_task($$$)\ndef $NAME($$$): $$$", label: "celery-task" },
  { fn: "symbols", lang: "python", pattern: "@pytest.fixture\ndef $NAME($$$): $$$", label: "fixture" },
  { fn: "symbols", lang: "python", pattern: "@pytest.fixture($$$)\ndef $NAME($$$): $$$", label: "fixture" },
  { fn: "symbols", lang: "python", pattern: "def test_$NAME($$$): $$$", label: "test-case" },
  { fn: "symbols", lang: "python", pattern: "async def test_$NAME($$$): $$$", label: "test-case" },

  // --- 跨层：导入抽取 / API 路径（--no-crosslayer 时跳过） ---
  { fn: "import", lang: "python", pattern: "from $M import $$$", metavar: "M", clean: "raw" , crosslayer: true },
  { fn: "import", lang: "python", pattern: "import $M", metavar: "M", clean: "as-strip" , crosslayer: true },
  { fn: "urls", lang: "python", kind: "call", label: "api-call" , crosslayer: true },
  { fn: "urls", lang: "python", kind: "decorator", label: "api-route" , crosslayer: true },
];
