// React / TypeScript / JavaScript / TSX 语言规则 — 自 rules_typescript.sh 逐条机械移植（勿手改 pattern，改动须与 Bash 版同步）
// crosslayer: true 的规则仅在 CROSSLAYER=1 时执行（对应 Bash 版 if CROSSLAYER==1 块）

export const RULES = [
  { fn: "symbols", lang: "typescript", pattern: "interface $NAME { $$$ }", label: "interface" },
  { fn: "symbols", lang: "typescript", pattern: "interface $NAME extends $$$ { $$$ }", label: "interface" },
  { fn: "symbols", lang: "typescript", pattern: "type $NAME = $$$", label: "type" },
  { fn: "symbols", lang: "typescript", pattern: "type $NAME<$$$> = $$$", label: "generic-type" },
  { fn: "symbols", lang: "typescript", pattern: "enum $NAME { $$$ }", label: "enum" },
  { fn: "symbols", lang: "typescript", pattern: "export enum $NAME { $$$ }", label: "enum" },
  { fn: "symbols", lang: "typescript", pattern: "class $NAME { $$$ }", label: "class" },
  { fn: "symbols", lang: "typescript", pattern: "class $NAME extends $$$ { $$$ }", label: "class" },
  { fn: "symbols", lang: "typescript", pattern: "class $NAME implements $$$ { $$$ }", label: "class" },
  { fn: "symbols", lang: "typescript", pattern: "abstract class $NAME { $$$ }", label: "abstract-class" },
  { fn: "symbols", lang: "javascript", pattern: "class $NAME { $$$ }", label: "class" },
  { fn: "symbols", lang: "javascript", pattern: "class $NAME extends $$$ { $$$ }", label: "class" },
  { fn: "symbols", lang: "typescript", pattern: "@Controller($$$)\nexport class $NAME { $$$ }", label: "nest-controller" },
  { fn: "symbols", lang: "typescript", pattern: "@Injectable()\nexport class $NAME { $$$ }", label: "nest-service" },
  { fn: "symbols", lang: "typescript", pattern: "@Module($$$)\nexport class $NAME { $$$ }", label: "nest-module" },
  { fn: "symbols", lang: "typescript", pattern: "@Entity($$$)\nexport class $NAME { $$$ }", label: "typeorm-entity" },
  { fn: "kinds", lang: "typescript", kind: "method_definition", label: "method" },
  { fn: "kinds", lang: "tsx", kind: "method_definition", label: "method" },
  { fn: "kinds", lang: "javascript", kind: "method_definition", label: "method" },
  { fn: "symbols", lang: "typescript", pattern: "function $NAME($$$) { $$$ }", label: "func" },
  { fn: "symbols", lang: "typescript", pattern: "function $NAME($$$): $RET { $$$ }", label: "func" },
  { fn: "symbols", lang: "typescript", pattern: "async function $NAME($$$) { $$$ }", label: "async-func" },
  { fn: "symbols", lang: "typescript", pattern: "export function $NAME($$$) { $$$ }", label: "func" },
  { fn: "symbols", lang: "typescript", pattern: "export function $NAME($$$): $RET { $$$ }", label: "func" },
  { fn: "symbols", lang: "typescript", pattern: "export async function $NAME($$$) { $$$ }", label: "async-func" },
  { fn: "symbols", lang: "typescript", pattern: "export async function $NAME($$$): $RET { $$$ }", label: "async-func" },
  { fn: "symbols", lang: "typescript", pattern: "export default function $NAME($$$) { $$$ }", label: "default-func" },
  { fn: "symbols", lang: "typescript", pattern: "export default async function $NAME($$$) { $$$ }", label: "default-async-func" },
  { fn: "symbols", lang: "javascript", pattern: "function $NAME($$$) { $$$ }", label: "func" },
  { fn: "symbols", lang: "javascript", pattern: "async function $NAME($$$) { $$$ }", label: "async-func" },
  { fn: "symbols", lang: "javascript", pattern: "export default function $NAME($$$) { $$$ }", label: "default-func" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = ($$$) => { $$$ }", label: "const-func" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = async ($$$) => { $$$ }", label: "async-const-func" },
  { fn: "symbols", lang: "typescript", pattern: "const $NAME = ($$$) => { $$$ }", label: "const-func" },
  { fn: "symbols", lang: "typescript", pattern: "const $NAME = async ($$$) => { $$$ }", label: "async-const-func" },
  { fn: "symbols", lang: "javascript", pattern: "export const $NAME = ($$$) => { $$$ }", label: "const-func" },
  { fn: "symbols", lang: "javascript", pattern: "export const $NAME = async ($$$) => { $$$ }", label: "async-const-func" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = $$$", label: "const" },
  { fn: "symbols", lang: "tsx", pattern: "export const $NAME = $$$", label: "const" },
  { fn: "symbols", lang: "javascript", pattern: "export const $NAME = $$$", label: "const" },
  { fn: "symbols", lang: "tsx", pattern: "export const $NAME: React.FC<$$$> = ($$$) => { $$$ }", label: "react-component" },
  { fn: "symbols", lang: "tsx", pattern: "export const $NAME: FC<$$$> = ($$$) => { $$$ }", label: "react-component" },
  { fn: "symbols", lang: "tsx", pattern: "export const $NAME = ($$$) => { $$$ }", label: "react-component" },
  { fn: "symbols", lang: "tsx", pattern: "export function $NAME($$$) { $$$ }", label: "react-component" },
  { fn: "symbols", lang: "tsx", pattern: "export function $NAME($$$): $RET { $$$ }", label: "react-component" },
  { fn: "symbols", lang: "tsx", pattern: "function $NAME($$$) { $$$ }", label: "react-component" },
  { fn: "symbols", lang: "tsx", pattern: "function $NAME($$$): $RET { $$$ }", label: "react-component" },
  { fn: "symbols", lang: "tsx", pattern: "export default function $NAME($$$) { $$$ }", label: "default-component" },
  { fn: "symbols", lang: "tsx", pattern: "export const $NAME = forwardRef($$$)", label: "forward-ref-component" },
  { fn: "symbols", lang: "tsx", pattern: "export const $NAME = memo($$$)", label: "memo-component" },
  { fn: "symbols", lang: "tsx", pattern: "export const $NAME = createContext($$$)", label: "react-context" },
  { fn: "symbols", lang: "typescript", pattern: "export function use$NAME($$$) { $$$ }", label: "custom-hook" },
  { fn: "symbols", lang: "typescript", pattern: "export const use$NAME = ($$$) => { $$$ }", label: "custom-hook" },
  { fn: "symbols", lang: "tsx", pattern: "export function use$NAME($$$) { $$$ }", label: "custom-hook" },
  { fn: "symbols", lang: "tsx", pattern: "export const use$NAME = ($$$) => { $$$ }", label: "custom-hook" },
  { fn: "symbols", lang: "typescript", pattern: "export default defineComponent($$$)", label: "vue-component" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = defineComponent($$$)", label: "vue-component" },
  { fn: "symbols", lang: "javascript", pattern: "export default defineComponent($$$)", label: "vue-component" },
  { fn: "symbols", lang: "typescript", pattern: "const props = defineProps<$$$>()", label: "vue-props" },
  { fn: "symbols", lang: "typescript", pattern: "const emit = defineEmits<$$$>()", label: "vue-emits" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = create($$$)", label: "zustand-store" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = create<$$$>()($$$)", label: "zustand-store" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = defineStore($$$)", label: "pinia-store" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = createSlice($$$)", label: "redux-slice" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = createAsyncThunk($$$)", label: "redux-thunk" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = z.object($$$)", label: "zod-schema" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = z.discriminatedUnion($$$)", label: "zod-schema" },
  { fn: "symbols", lang: "typescript", pattern: "const $NAME = z.object($$$)", label: "zod-schema" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = object($$$)", label: "valibot-schema" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = Type.Object($$$)", label: "typebox-schema" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = new Hono($$$)", label: "hono-app" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = Router($$$)", label: "express-router" },
  { fn: "route", lang: "typescript", pattern: "app.get($PATH, $NAME)", label: "http-get" },
  { fn: "route", lang: "typescript", pattern: "app.post($PATH, $NAME)", label: "http-post" },
  { fn: "route", lang: "typescript", pattern: "app.put($PATH, $NAME)", label: "http-put" },
  { fn: "route", lang: "typescript", pattern: "app.delete($PATH, $NAME)", label: "http-delete" },
  { fn: "route", lang: "typescript", pattern: "router.get($PATH, $NAME)", label: "http-get" },
  { fn: "route", lang: "typescript", pattern: "router.post($PATH, $NAME)", label: "http-post" },
  { fn: "symbols", lang: "typescript", pattern: "export const $NAME = router({$$$})", label: "trpc-router" },

  // --- 跨层：导入抽取 / API 路径（--no-crosslayer 时跳过） ---
  { fn: "importKind", lang: "typescript", kind: "import_statement", mode: "js" , crosslayer: true },
  { fn: "importKind", lang: "tsx", kind: "import_statement", mode: "js" , crosslayer: true },
  { fn: "importKind", lang: "javascript", kind: "import_statement", mode: "js" , crosslayer: true },
  { fn: "import", lang: "typescript", pattern: "require($PATH)", metavar: "PATH", clean: "raw" , crosslayer: true },
  { fn: "import", lang: "tsx", pattern: "require($PATH)", metavar: "PATH", clean: "raw" , crosslayer: true },
  { fn: "import", lang: "javascript", pattern: "require($PATH)", metavar: "PATH", clean: "raw" , crosslayer: true },
  { fn: "urls", lang: "typescript", kind: "call_expression", label: "api-call" , crosslayer: true },
  { fn: "urls", lang: "tsx", kind: "call_expression", label: "api-call" , crosslayer: true },
  { fn: "urls", lang: "javascript", kind: "call_expression", label: "api-call" , crosslayer: true },
  { fn: "urls", lang: "typescript", kind: "decorator", label: "api-route" , crosslayer: true },
  { fn: "urls", lang: "tsx", kind: "decorator", label: "api-route" , crosslayer: true },
];
