// ==============================================================================
// src/freshness.mjs — git 元数据 + header 写入（collect_freshness / write_freshness_header 等价层）
// ==============================================================================

import { execFileSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { mkdirSync } from 'node:fs'
import path from 'node:path'
import { VERSION } from './version.mjs'

const require = createRequire(import.meta.url)

function napiVersion() {
  try {
    return require('@ast-grep/napi/package.json').version
  } catch {
    return 'unavailable'
  }
}

// collect_freshness：读取 HEAD SHA、worktree 状态。无 Git 仓库时不失败，写 unavailable。
export function collectFreshness(targetDirAbs) {
  let commit = 'unavailable'
  let worktree = 'unavailable'
  let inGit = false
  try {
    execFileSync('git', ['-C', targetDirAbs, 'rev-parse', '--git-dir'], { stdio: 'ignore' })
    inGit = true
  } catch { inGit = false }
  if (inGit) {
    try {
      commit = execFileSync('git', ['-C', targetDirAbs, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim()
    } catch { commit = 'unavailable' }
    let status = ''
    try {
      status = execFileSync('git', ['-C', targetDirAbs, 'status', '--porcelain'], { encoding: 'utf8' })
    } catch { status = '' }
    worktree = status.trim() !== '' ? 'dirty' : 'clean'
  }
  return { commit, worktree }
}

// write_freshness_header：返回 header 行数组（含结尾空行）。HEADER_LINES = 行数。
// extraLines 为额外注释行内容（不带 '# ' 前缀，由本函数统一加）。
export function buildFreshnessHeader({ name, sourcePath, merge = false, extraLines = [], langList }) {
  const { commit, worktree } = merge
    ? { commit: 'unavailable', worktree: 'unavailable' }
    : collectFreshness(sourcePath)
  const lines = []
  lines.push(`# Architecture Map: ${name}`)
  lines.push(merge
    ? '# Source Path: (merged — 见下方逐模块 Merged Source 行)'
    : `# Source Path: ${sourcePath}`)
  lines.push(`# Generated by: ast-grep napi engine (code-atlas.mjs v${VERSION})`)
  for (const e of extraLines) lines.push(`# ${e}`)
  lines.push(merge ? '# Source Commit: unavailable (merged)' : `# Source Commit: ${commit}`)
  lines.push(merge ? '# Worktree: unavailable (merged)' : `# Worktree: ${worktree}`)
  lines.push(`# Scanner Version: ${VERSION}`)
  lines.push(`# ast-grep Version: ${napiVersion()}`)
  lines.push(`# Languages: ${langList.join(',')}`)
  lines.push('')
  return lines
}

export function ensureOutputDir(outputFile) {
  mkdirSync(path.dirname(outputFile), { recursive: true })
}
